<template>
    <footer v-if="loaded" class="h-24 bg-yellow-400 text-center flex flex-col justify-center ">
        <h5 class="text-sm font-bold">Debug log version <span class="font-normal" v-html="asCode(data.debug_version)"></span></h5>
        <h5 class="text-sm font-bold">Generated by <img v-if="data.generated_by_uuid" class="inline" :src="`https://crafthead.net/helm/${data.generated_by_uuid}/16`"> <span class="font-normal">{{ data.generated_by_name }}</span></h5>
        <h5 class="text-sm font-bold">Raw JSON <a :href="`https://paste.rkslot.nl/${key}`" target="_blank"><span class="font-normal">https://paste.rkslot.nl/{{ key }}</span></a></h5>
    </footer>
</template>

<script>
import functions from '../functions.js';

export default {
    created() {
        this.asCode = functions.asCode;
    },
    props: [
        'loaded',
        'data'
    ]
}
</script>
